from zoro_utils.impl.implementation_singleton import zoro_utils_implementation as _zoro_utils

zoro_init=_zoro_utils.zoro_init
get_logger=_zoro_utils.get_logger

start_service=_zoro_utils.start_service

get_parameters=_zoro_utils.get_parameters
set_parameters=_zoro_utils.set_parameters



hello=_zoro_utils.hello
client_init=_zoro_utils.client_init
get_description=_zoro_utils.get_description
get_values=_zoro_utils.get_values
update_parameters=_zoro_utils.update_parameters
